force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>チーム</label>
    <nameField>
        <label>チーム名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/address_city__c.field-meta.xml
<CustomField>
    <fullName>address_city__c</fullName>
    <label>address_city</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/franchise_code__c.field-meta.xml
<CustomField>
    <fullName>franchise_code__c</fullName>
    <label>franchise_code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Team__c/fields/league_full__c.field-meta.xml
<CustomField>
    <fullName>league_full__c</fullName>
    <label>league_full</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/league_id__c.field-meta.xml
<CustomField>
    <fullName>league_id__c</fullName>
    <externalId>true</externalId>
    <label>league_id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/name_display_full__c.field-meta.xml
<CustomField>
    <fullName>name_display_full__c</fullName>
    <label>name_display_full</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/sport_id__c.field-meta.xml
<CustomField>
    <fullName>sport_id__c</fullName>
    <externalId>true</externalId>
    <label>sport_id</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/store_url__c.field-meta.xml
<CustomField>
    <fullName>store_url__c</fullName>
    <label>store_url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/team_id__c.field-meta.xml
<CustomField>
    <fullName>team_id__c</fullName>
    <externalId>true</externalId>
    <label>team_id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TeamInfoUpsert.cls
public class TeamInfoUpsert {
    public static void TeamInfoUpsert(){
        List<Object> Teams = MlbCallouts.TeamGetCallout();
        System.debug('Teams: ' + Teams);
        
        //upsert用のリスト作成
        List<Team__c> upsertList = new List<Team__c>();
        
        for(Object team : Teams){
        	Map<String, Object> t = (Map<String, Object>)team;
            Team__c teamRecord = new Team__c();
            teamRecord.team_id__c = (String)t.get('team_id');
            teamRecord.name = (String)t.get('name_display_full');
            teamRecord.franchise_code__c = (String)t.get('franchise_cSode');
            teamRecord.address_city__c = (String)t.get('address_city');
            teamRecord.store_url__c = (String)t.get('store_url');
            teamRecord.venue_name__c = (String)t.get('venue_name');
            teamRecord.name_display_full__c = (String)t.get('name');
            teamRecord.league_full__c = (String)t.get('league_full');
            teamRecord.league_id__c = (String)t.get('league_id');
            teamRecord.sport_id__c = (String)t.get('sport_id');
            upsertList.add(teamRecord);
            System.debug('teamRecord: '+teamRecord);
        }
       	if(upsertList.size() > 0 ){
        	upsert upsertList team_id__c;
        }
    }
}