force-app/main/default/objects/player__c/player__c.object-meta.xml
<CustomObject>
    <label>選手</label>
    <nameField>
        <label>選手名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/player__c/fields/player_id__c.field-meta.xml
<CustomField>
    <fullName>player_id__c</fullName>
    <externalId>true</externalId>
    <label>player_id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/SeasonHittingStats__c.object-meta.xml
<CustomObject>
    <label>打者成績(シーズン)</label>
    <nameField>
        <label>打者成績No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SeasonHittingStats__c/fields/ab__c.field-meta.xml
<CustomField>
    <fullName>ab__c</fullName>
    <label>打数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/ao__c.field-meta.xml
<CustomField>
    <fullName>ao__c</fullName>
    <label>フライアウト数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/avg__c.field-meta.xml
<CustomField>
    <fullName>avg__c</fullName>
    <label>打率</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/bb__c.field-meta.xml
<CustomField>
    <fullName>bb__c</fullName>
    <label>四球</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/cs__c.field-meta.xml
<CustomField>
    <fullName>cs__c</fullName>
    <label>盗塁失敗数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/go__c.field-meta.xml
<CustomField>
    <fullName>go__c</fullName>
    <label>ゴロ</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/go_ao__c.field-meta.xml
<CustomField>
    <fullName>go_ao__c</fullName>
    <inlineHelpText>ゴロ（GB）の総数をフライ（FB）の総数で割った数</inlineHelpText>
    <label>ゴロ/フライ比率</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/h__c.field-meta.xml
<CustomField>
    <fullName>h__c</fullName>
    <label>安打</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/hbp__c.field-meta.xml
<CustomField>
    <fullName>hbp__c</fullName>
    <label>死球</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/hr__c.field-meta.xml
<CustomField>
    <fullName>hr__c</fullName>
    <label>本塁打数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <description>シーズン_playerId</description>
    <externalId>true</externalId>
    <label>キー</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/league__c.field-meta.xml
<CustomField>
    <fullName>league__c</fullName>
    <label>リーグ名</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/lob__c.field-meta.xml
<CustomField>
    <fullName>lob__c</fullName>
    <label>残塁</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/np__c.field-meta.xml
<CustomField>
    <fullName>np__c</fullName>
    <inlineHelpText>打席中に相手投手が投げた投球数</inlineHelpText>
    <label>被投球数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/obp__c.field-meta.xml
<CustomField>
    <fullName>obp__c</fullName>
    <label>出塁率</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/ops__c.field-meta.xml
<CustomField>
    <fullName>ops__c</fullName>
    <description>出塁率＋長打率</description>
    <label>OPS</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/player_id__c.field-meta.xml
<CustomField>
    <fullName>player_id__c</fullName>
    <label>選手</label>
    <referenceTo>player__c</referenceTo>
    <relationshipLabel>打者成績(シーズン)</relationshipLabel>
    <relationshipName>players_HittingStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/ppa__c.field-meta.xml
<CustomField>
    <fullName>ppa__c</fullName>
    <inlineHelpText>1打席あたりの被投球数</inlineHelpText>
    <label>P/PA</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/R__c.field-meta.xml
<CustomField>
    <fullName>R__c</fullName>
    <label>得点</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/rbi__c.field-meta.xml
<CustomField>
    <fullName>rbi__c</fullName>
    <label>打点</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/sb__c.field-meta.xml
<CustomField>
    <fullName>sb__c</fullName>
    <label>盗塁</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/sf__c.field-meta.xml
<CustomField>
    <fullName>sf__c</fullName>
    <label>犠牲フライ</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/slg__c.field-meta.xml
<CustomField>
    <fullName>slg__c</fullName>
    <inlineHelpText>長打率 = 塁打 ÷ 打数</inlineHelpText>
    <label>長打率</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/so__c.field-meta.xml
<CustomField>
    <fullName>so__c</fullName>
    <label>三振</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/tb__c.field-meta.xml
<CustomField>
    <fullName>tb__c</fullName>
    <label>塁打総数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/team_abbrev__c.field-meta.xml
<CustomField>
    <fullName>team_abbrev__c</fullName>
    <label>チーム名</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/tpa__c.field-meta.xml
<CustomField>
    <fullName>tpa__c</fullName>
    <label>総打席数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/wo__c.field-meta.xml
<CustomField>
    <fullName>wo__c</fullName>
    <label>Walk Off</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeasonHittingStats__c/fields/xbh__c.field-meta.xml
<CustomField>
    <fullName>xbh__c</fullName>
    <inlineHelpText>２塁打＋３塁打＋本塁打を足した長打数</inlineHelpText>
    <label>長打数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetSeasonPitchingStatsDetailBatch.cls
public class GetSeasonPitchingStatsDetailBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    String Season = '2021';
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, player_id__c FROM player__c';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<player__c> targetRecords) {
        //player_idのSetを作成
        Set<String> playerIdSet = new Set<String>();
        String str = '';
        //引数用の文字列作成
        for(player__c player : targetRecords){
            playerIdSet.add(player.player_id__c);
            str += '&season=\'';
            str += Season;
            str += '\'';
            str += '&player_id=\'';
            str += player.player_id__c;
            str += '\'';
        }
        System.debug('str: '+str);
        //upsert用のリスト作成
        Map<String , SeasonHittingStats__c> upsertPlayerMap = new Map<String , SeasonHittingStats__c>();
        List<Object> playerHitStats = MlbCallouts.SeasonHittingStatsGetCallout(str);
        System.debug('playerHitStats: ' + playerHitStats);
        if(playerHitStats == null){
            return;
        }
        for(Object stats : playerHitStats){
            Map<String, Object> s = (Map<String, Object>)stats;
            SeasonHittingStats__c targetPlayerStats = new SeasonHittingStats__c();
            targetPlayerStats.player_id__r = new player__c(player_id__c=(String)s.get('player_id'));
            targetPlayerStats.season__c = (String)s.get('season');
            targetPlayerStats.key__c = (String)s.get('season')+ '_' + (String)s.get('player_id');
            targetPlayerStats.Name = (String)s.get('season');
            targetPlayerStats.league__c = (String)s.get('league');
            targetPlayerStats.team_abbrev__c = (String)s.get('team_abbrev');
            targetPlayerStats.ops__c = (String)s.get('ops') == '-.--'  || (String)s.get('ops') == '.---'? 0 : Decimal.valueOf((String)s.get('ops')) ;
            targetPlayerStats.ppa__c = (String)s.get('ppa') == '-.--'  || (String)s.get('ppa') == '.---'? 0 : Decimal.valueOf((String)s.get('ppa'));
            targetPlayerStats.wo__c = Decimal.valueOf((String)s.get('wo'));
            targetPlayerStats.go__c = Decimal.valueOf((String)s.get('go'));
            targetPlayerStats.go_ao__c  = (String)s.get('go_ao') == '*.**' || (String)s.get('go_ao') == '-.--'|| (String)s.get('go_ao') == '.---' ? 0 : Decimal.valueOf((String)s.get('go_ao'));
            targetPlayerStats.ao__c  = Decimal.valueOf((String)s.get('ao'));
            targetPlayerStats.so__c  = Decimal.valueOf((String)s.get('so'));
            targetPlayerStats.obp__c = (String)s.get('obp') == '-.--' || (String)s.get('obp') == '.---'? 0 : Decimal.valueOf((String)s.get('obp'));
            targetPlayerStats.bb__c = Decimal.valueOf((String)s.get('bb'));
            targetPlayerStats.tb__c = Decimal.valueOf((String)s.get('tb'));
            targetPlayerStats.h__c = Decimal.valueOf((String)s.get('h'));
            targetPlayerStats.R__c = Integer.valueOf((String)s.get('r'));
            targetPlayerStats.ab__c = Integer.valueOf((String)s.get('ab'));
            targetPlayerStats.rbi__c = Integer.valueOf((String)s.get('rbi'));
            targetPlayerStats.avg__c = (String)s.get('avg') == '-.--' || (String)s.get('avg') == '.---' ? 0 : Decimal.valueOf((String)s.get('avg'));
            targetPlayerStats.ibb__c = Integer.valueOf((String)s.get('ibb'));
            targetPlayerStats.hr__c = Integer.valueOf((String)s.get('hr'));
            targetPlayerStats.hbp__c = Integer.valueOf((String)s.get('hbp'));
            targetPlayerStats.lob__c = Integer.valueOf((String)s.get('lob'));
            targetPlayerStats.sac__c = Integer.valueOf((String)s.get('sac'));
            targetPlayerStats.sf__c = Decimal.valueOf((String)s.get('sf'));
            targetPlayerStats.sb__c = Decimal.valueOf((String)s.get('sb'));
            targetPlayerStats.cs__c = Decimal.valueOf((String)s.get('cs'));
            targetPlayerStats.tpa__c = Decimal.valueOf((String)s.get('tpa'));
            targetPlayerStats.np__c = Decimal.valueOf((String)s.get('np'));
            targetPlayerStats.g__c = Decimal.valueOf((String)s.get('g'));
            targetPlayerStats.xbh__c = Decimal.valueOf((String)s.get('xbh'));
            targetPlayerStats.slg__c = (String)s.get('slg') == '-.--'  || (String)s.get('slg') == '.---'? 0 : Decimal.valueOf((String)s.get('slg'));
            upsertPlayerMap.put(targetPlayerStats.player_id__c, targetPlayerStats);
            System.debug('targetPlayerStats: '+targetPlayerStats);
        }
        if(upsertPlayerMap.size() > 0 ){
            upsert upsertPlayerMap.values() key__c;
        }
    }
    public void finish(Database.BatchableContext bc) {
    }
}