force-app/main/default/objects/player__c/player__c.object-meta.xml
<CustomObject>
    <label>選手</label>
    <nameField>
        <label>選手名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/player__c/fields/player_id__c.field-meta.xml
<CustomField>
    <fullName>player_id__c</fullName>
    <externalId>true</externalId>
    <label>player_id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>チーム</label>
    <nameField>
        <label>チーム名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/team_id__c.field-meta.xml
<CustomField>
    <fullName>team_id__c</fullName>
    <externalId>true</externalId>
    <label>team_id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/X40_MAN_ROSTER__c/X40_MAN_ROSTER__c.object-meta.xml
<CustomObject>
    <label>40-MAN ROSTER</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X40_MAN_ROSTER__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>選手</label>
    <referenceTo>player__c</referenceTo>
    <relationshipLabel>40-MAN ROSTER</relationshipLabel>
    <relationshipName>Players_40_MAN_ROSTER</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X40_MAN_ROSTER__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>チーム</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>40-MAN ROSTER</relationshipLabel>
    <relationshipName>Teams_40_MAN_ROSTER</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Get40ManRoaster.cls
public class Get40ManRoaster {
    public static void Get40ManRoaster(){
        //チームレコードを一括取得
        List<Team__c> teamRecordList = [SELECT 
                                       	Id,
                                       	team_id__c
                                       FROM
                                       	Team__c];
        //team_idのSetを作成
        Set<String> teamIdSet = new Set<String>();
        for(Team__c team : teamRecordList){
            teamIdSet.add(team.team_id__c);
        }
        
        //現時点の40-MAN ROSTERレコードを取得
        Map<String,X40_MAN_ROSTER__c> existRoaterMap = new Map<String,X40_MAN_ROSTER__c>();
        for(X40_MAN_ROSTER__c existRoater : [SELECT id, Team__r.team_id__c, Player__r.player_id__c FROM X40_MAN_ROSTER__c]){
            existRoaterMap.put(existRoater.Team__r.team_id__c+'_'+existRoater.Player__r.player_id__c, existRoater);
        }
        //ロースター除外用のリスト
        List<X40_MAN_ROSTER__c> deleteRoater = new List<X40_MAN_ROSTER__c>();
        //insertMap作成
        Map<String,X40_MAN_ROSTER__c> insertPlayerMap = new Map<String,X40_MAN_ROSTER__c>();
        //continuMap作成
        Map<String,X40_MAN_ROSTER__c> continuePlayerMap = new Map<String,X40_MAN_ROSTER__c>();
        
        for(String id : teamIdSet){
        	List<Object> rosterPlayers = MlbCallouts.Roster40MANGetCallout(id);
            System.debug('rosterPlayers: ' + rosterPlayers);

        	for(Object player : rosterPlayers){
        		Map<String, Object> p = (Map<String, Object>)player;
                X40_MAN_ROSTER__c  targetPlayer = new X40_MAN_ROSTER__c ();
                targetPlayer.Name = (String)p.get('name_display_first_last')+'_'+(String)p.get('team_abbrev');
                targetPlayer.Team__r = new Team__c(team_id__c=(String)p.get('team_id'));
                targetPlayer.Player__r = new player__c(player_id__c=(String)p.get('player_id'));
                //既存のロースターと同じ選手がいる場合は、リストから除外
                if(existRoaterMap.containsKey((String)p.get('team_id')+'_'+(String)p.get('player_id'))){
                    continuePlayerMap.put((String)p.get('team_id')+'_'+(String)p.get('player_id'),targetPlayer);
                    continue;
                }
                insertPlayerMap.put((String)p.get('team_id')+'_'+(String)p.get('player_id'),targetPlayer);
            }
            //ロースター除外の選手の洗い出し
            for(String existKey :existRoaterMap.keyset()){
                if(continuePlayerMap.containsKey(existKey) != false && insertPlayerMap.containsKey(existKey) != false){
                    deleteRoater.add(existRoaterMap.get(existKey));
                }
            }
        }
        insert insertPlayerMap.values();
    }
}