force-app/main/default/objects/DailyHittingStats__c/DailyHittingStats__c.object-meta.xml
<CustomObject>
    <label>打者成績(デイリー)</label>
    <nameField>
        <displayFormat>DB-{0000000}</displayFormat>
        <label>打者成績(デイリー)No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyHittingStats__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>日付</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DailyHittingStats__c/fields/HR__c.field-meta.xml
<CustomField>
    <fullName>HR__c</fullName>
    <label>HR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DailyHittingStats__c/fields/player__c.field-meta.xml
<CustomField>
    <fullName>player__c</fullName>
    <label>選手</label>
    <referenceTo>player__c</referenceTo>
    <relationshipLabel>打者成績(デイリー)</relationshipLabel>
    <relationshipName>DailyBat_Player</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DailyHittingStats__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <formula>TEXT(YEAR( date__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>シーズン</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DailyHittingStats__c/fields/TotalHR__c.field-meta.xml
<CustomField>
    <fullName>TotalHR__c</fullName>
    <label>累積HR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/player__c/player__c.object-meta.xml
<CustomObject>
    <label>選手</label>
    <nameField>
        <label>選手名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/player__c/fields/name_display_first_last__c.field-meta.xml
<CustomField>
    <fullName>name_display_first_last__c</fullName>
    <label>name_display_first_last</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/player__c/fields/player_id__c.field-meta.xml
<CustomField>
    <fullName>player_id__c</fullName>
    <externalId>true</externalId>
    <label>player_id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CalculationTotalHrBatch.cls
public class CalculationTotalHrBatch implements Database.Batchable<sObject>, Database.Stateful {
    String Season = '2021';
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, player_id__c, name_display_first_last__c FROM player__c';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<player__c> targetRecords) {
        Set<String> playerIdSet = new Set<String>();
        for(player__c p : targetRecords){
            playerIdSet.add(p.player_id__c);
        }
        List<DailyHittingStats__c> upsertDailyHitting = new  List<DailyHittingStats__c>();
        List<player__c> playerList = [SELECT name_display_first_last__c,(SELECT id, HR__c, TotalHR__c, Date__c, Season__c FROM DailyBat_Player__r ORDER BY Date__c) FROM player__c WHERE player_id__c IN: playerIdSet ];
        for(player__c p : playerList){
			List<DailyHittingStats__c> dailyHitting = p.DailyBat_Player__r;
            if(dailyHitting.isEmpty()){
                continue;
            }
            Decimal totalHr = 0;
            for(DailyHittingStats__c h : dailyHitting){
                if(h.Season__c != Season){
                    continue;
                }
                totalHr += h.HR__c;
                h.TotalHR__c = totalHr;
                upsertDailyHitting.add(h);
            }
        }
        upsert upsertDailyHitting;
    }
    public void finish(Database.BatchableContext bc) {
    }
}